### ISSUE TITLE
Throws undefined method `+' for nil:NilClass when image has no classes

### ISSUE THREAD

**Issue by tommiciak** [bastienrobert/middleman-async-image#1]
When I use `image_async_tag` helper without specifying `class:` parameter I get this error on line 51.

**Comment by bastienrobert** [comment]
Hi, should be fixed in #2. Please upgrade the gem to version 0.0.4 (https://github.com/bastienrobert/middleman-async-image/releases/tag/0.0.4)

**Comment by tommiciak** [comment]
Can confirm, thanks for the quick response 🙂
